# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageSegmenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MediaPipeTasksVision', '0.10.8'

  target 'ImageSegmenterTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'ImageSegmenterUITests' do
  inherit! :search_paths
  # Pods for testing
end

