package com.google.mediapipe.tasks.npu

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

abstract class GenerateCodeTask : DefaultTask() {

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    abstract val projectVersion: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val targetPackageName = packageName.get()
        val targetClassName = className.get()
        val version = projectVersion.get()
        val buildTime = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).format(Date())

        val fileContent = """
            package $targetPackageName
            
            /**
             * This file is generated automatically by the code-generator plugin.
             * Do not edit this file manually.
             */
            object $targetClassName {
                const val VERSION = "$version"
                const val BUILD_TIME = "$buildTime"
            }
        """.trimIndent()

        val outputFolder = outputDir.get().asFile.resolve(targetPackageName.replace('.', '/'))
        outputFolder.mkdirs()
        outputFolder.resolve("$targetClassName.kt").writeText(fileContent)

        println("✅ Generated $targetClassName.kt in $targetPackageName")
    }
}