# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GestureRecognizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GestureRecognizer
  pod 'MediaPipeTasksVision', '0.10.14'

end

target 'GestureRecognizerTests' do
  inherit! :search_paths
  # Pods for testing
end
