import MediaPipeTasksVision
import Observation
import SwiftUI

@Observable
@MainActor
final class InteractiveSegmenterViewModel {
  /// The original image selected by the user or the sample image.
  var inputImage: UIImage?
  /// The segmentation mask generated by the model, ready for display.
  var maskImage: UIImage?
  /// The history of strokes drawn by the user on the current image.
  var strokes: [Stroke] = []
  /// A user-facing message indicating the current status or error.
  var statusMessage: String = "Ready"
  /// Indicates whether a segmentation or initialization operation is in progress.
  var isBusy: Bool = false

  /// The underlying Interactive Segmenter actor runner.
  @ObservationIgnored private let segmenterRunner = InteractiveSegmenterRunner()
  /// The current image being processed.
  @ObservationIgnored private var image: MPImage?
  /// The error encountered during initialization, if any.
  @ObservationIgnored private var initializationError: Error?
  /// Tracker for keeping the timeout task so it can be canceled.
  @ObservationIgnored private var busyTimeoutTracker: Task<Void, Never>?
  /// Reusable Core Image context for pixel buffer to CGImage operations.
  @ObservationIgnored private let ciContext = CIContext(options: [.cacheIntermediates: false])

  private enum Constants {
    static let modelName = "interactive_segmentation"
    static let modelExtension = "task"
    static let sampleImageName = "cats_and_dogs"
    static let sampleImageExtension = "jpg"
    static let busyTimeout: TimeInterval = 10.0
  }

  init() {
  }

  /// Starts the view model by setting up the segmenter and loading the sample image.
  func start() async {
    await setupSegmenter()
    loadSampleImage()
  }

  /// Sets up the segmentation model in a background task.
  private func setupSegmenter() async {
    setBusy(true, status: "Initializing model...")

    do {
      guard
        let modelPath = Bundle.main.path(
          forResource: Constants.modelName, ofType: Constants.modelExtension)
      else {
        let err = NSError(
          domain: "InteractiveSegmenter", code: -1,
          userInfo: [
            NSLocalizedDescriptionKey:
              "Failed to find model \(Constants.modelName).\(Constants.modelExtension)"
          ])
        throw err
      }

      try await segmenterRunner.setup(modelPath: modelPath)
      initializationError = nil
      setBusy(false, status: "Ready")
    } catch {
      initializationError = error
      if (error as NSError).code == -1 {
        setBusy(false, status: "Failed to find model")
      } else {
        setBusy(false, status: "Init error (see Console)")
      }
      print("Error initializing segmenter: \(error)")
    }
  }

  /// Loads the default sample image from the bundle and updates the segmenter.
  private func loadSampleImage() {
    let fullName = "\(Constants.sampleImageName).\(Constants.sampleImageExtension)"
    if let image = UIImage(named: fullName) {
      update(with: image)
      return
    }

    if let path = Bundle.main.path(
      forResource: Constants.sampleImageName, ofType: Constants.sampleImageExtension),
      let image = UIImage(contentsOfFile: path)
    {
      update(with: image)
      return
    }

    print("Failed to load image \(fullName)")
  }

  /// Updates the view model with a new image, resetting strokes and triggering feature extraction.
  ///
  /// - Parameter image: The new image to set.
  func update(with image: UIImage) {
    inputImage = image
    strokes.removeAll()
    maskImage = nil

    if let error = initializationError {
      setBusy(false, status: "Init error (see Console)")
      print("Initialization error: \(error)")
      return
    }

    setBusy(true, status: "Extracting features...")

    Task {
      do {
        let imageToSet = try MPImage(uiImage: image)

        try await segmenterRunner.set(image: imageToSet)

        self.image = imageToSet
        if let error = initializationError {
          setBusy(false, status: "Init error (see Console)")
          print("Initialization error: \(error)")
        } else {
          setBusy(false, status: "Ready")
          print("Image set successfully.")
        }
      } catch {
        setBusy(false, status: "Image error (see Console)")
        print("Error setting image: \(error)")
      }
    }
  }

  /// Performs segmentation using the current strokes on the current image.
  func performSegmentation() {
    if let error = initializationError {
      setBusy(false, status: "Init error (see Console)")
      print("Initialization error: \(error)")
      return
    }

    guard !strokes.isEmpty else {
      return
    }

    setBusy(true, status: "Segmenting...")

    Task {
      do {
        let maskImage = try await segmenterRunner.segment(strokes: strokes)

        if let maskImage {
          try await updateMaskUI(
            with: maskImage,
            orientation: inputImage?.imageOrientation ?? .up,
            scale: inputImage?.scale ?? 1.0)
        }
        setBusy(false, status: "Ready")
      } catch {
        setBusy(false, status: "Segmentation error (see Console)")
        print("Segmentation error: \(error)")
      }
    }
  }

  /// Clears all drawn strokes and the current segmentation mask.
  func clearStrokes() {
    strokes.removeAll()
    maskImage = nil
  }

  /// Updates the mask UI based on the output. Note this now extracts CGImages async.
  private func updateMaskUI(
    with maskImageResult: MPImage, orientation: UIImage.Orientation = .up, scale: CGFloat = 1.0
  ) async throws {
    switch maskImageResult.imageSourceType {
    case .image:
      if let image = maskImageResult.image, let cgImage = image.cgImage {
        maskImage = UIImage(cgImage: cgImage, scale: scale, orientation: orientation)
      } else {
        maskImage = maskImageResult.image
      }
    case .pixelBuffer:
      if let pixelBuffer = maskImageResult.pixelBuffer {
        maskImage = await Task.detached { [ciContext = ciContext] in
          return UIImage(
            pixelBuffer: pixelBuffer, ciContext: ciContext, orientation: orientation, scale: scale)
        }.value
      }
    case .sampleBuffer:
      print("SampleBuffer mask not supported")
    default:
      print("Unsupported mask image source type")
    }
  }
  /// Updates the busy state and limits long-running operations with a timeout.
  private func setBusy(_ busy: Bool, status: String? = nil) {
    isBusy = busy
    if let status = status {
      statusMessage = status
    }

    busyTimeoutTracker?.cancel()

    if busy {
      busyTimeoutTracker = Task { [weak self] in
        do {
          try await Task.sleep(nanoseconds: UInt64(Constants.busyTimeout * 1_000_000_000))
          if Task.isCancelled { return }
          self?.isBusy = false
          self?.statusMessage = "Operation timed out"
          print("Operation timed out: went over \(Constants.busyTimeout) seconds")
        } catch {
          // Task was cancelled
        }
      }
    }
  }
}

extension UIImage {
  /// Helper to convert a pixel buffer directly to a UIImage.
  internal convenience init?(
    pixelBuffer: CVPixelBuffer, ciContext: CIContext,
    orientation: UIImage.Orientation = .up, scale: CGFloat = 1.0
  ) {
    let ciImage = CIImage(cvPixelBuffer: pixelBuffer)
    guard
      let cgImage = ciContext.createCGImage(
        ciImage,
        from: CGRect(
          x: 0, y: 0, width: CVPixelBufferGetWidth(pixelBuffer),
          height: CVPixelBufferGetHeight(pixelBuffer)))
    else {
      return nil
    }
    self.init(cgImage: cgImage, scale: scale, orientation: orientation)
  }
}

/// An actor encapsulating the InteractiveSegmenter to guarantee serial,
/// thread-safe access to its underlying non-Sendable API.
actor InteractiveSegmenterRunner {
  private var segmenter: InteractiveSegmenter?

  func setup(modelPath: String) throws {
    let options = InteractiveSegmenterOptions()
    options.baseOptions.modelAssetPath = modelPath
    options.baseOptions.delegate = .GPU
    segmenter = try InteractiveSegmenter(options: options)
  }

  func set(image: MPImage) throws {
    // If the segmenter is not initialized, we cannot set the image.
    guard let segmenter else {
      throw NSError(
        domain: "InteractiveSegmenter", code: -1,
        userInfo: [NSLocalizedDescriptionKey: "Segmenter not initialized"])
    }
    _ = try segmenter.set(image: image)
  }

  func segment(strokes: [Stroke]) throws -> MPImage? {
    // If there is no segmenter, wait or return nil.
    guard let segmenter else { return nil }
    return try segmenter.segment(strokes: strokes)
  }
}
