# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaceDetector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksVision', '0.10.2-alpha-3'

  # Pods for FaceDetector
end

target 'FaceDetectorTests' do
  inherit! :search_paths
  # Pods for testing
end
