platform :ios, '15.0'

target 'FaceDetector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksVision', '0.10.14'

  # Pods for FaceDetector
end

target 'FaceDetectorTests' do
  inherit! :search_paths
  # Pods for testing
end
