platform :ios, '15.0'

target 'ObjectDetector' do

  use_frameworks!
  pod 'MediaPipeTasksVision', '0.10.5'

  # Pods for ObjectDetector
end

target 'ObjectDetectorTests' do
    inherit! :search_paths
    # Pods for testing
 end
