platform :ios, '15.0'

target 'ImageClassifier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksVision', '0.10.14'
end

target 'ImageClassifierTests' do
  inherit! :search_paths
  # Pods for testing
end
