# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageClassifier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksVision', '0.10.1-alpha-2'
end

target 'ImageClassifierTests' do
  inherit! :search_paths
  # Pods for testing
end
